

# This file was *autogenerated* from the file babai_error_finder.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_3329 = Integer(3329); _sage_const_120 = Integer(120); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_12 = Integer(12); _sage_const_50 = Integer(50); _sage_const_80 = Integer(80); _sage_const_34 = Integer(34)
load('../framework/LWE.sage')
load('../framework/utils.sage')

import pandas as pd
import time
from numpy.random import seed as np_seed
from numpy.random import randint as np_randint
from concurrent.futures import ProcessPoolExecutor, as_completed
from multiprocessing import cpu_count

nb_tests = _sage_const_1 
ring = _sage_const_0 

q = _sage_const_3329 
n = _sage_const_120 
m = n

def one_experiment(seed):

    set_random_seed(seed)
    assert(initial_seed() == seed)
    np_seed(seed=seed)

    start = time.time()
    sigma = sqrt(_sage_const_3 /_sage_const_2 )
    sigma_c = []
    mu = concatenate([_sage_const_0 ] * (m+n), [])
    d = m + n

    #Setting up Sigma
    for i in range(_sage_const_0 , n):
        sigma_c.append(((sigma / q) ** _sage_const_2 ) + (sigma**_sage_const_2  * n -_sage_const_1 )/_sage_const_12 )
    Sigma = block_matrix([[diagonal_matrix(sigma_c), zero_matrix(n)],
                          [zero_matrix(n),(sigma ** _sage_const_2 ) * identity_matrix(n)]])
    Sigma = Sigma * d #scale dimension (may have to remove)
    our_ebdd = EBDD(identity_matrix(d), Sigma, mu, None, calibrate_volume = False)
    D_s = build_Gaussian_law(sigma, _sage_const_50 )
    D_e = D_s

    #Creating LWE instance used for the hints
    if ring == _sage_const_1 :
        lwe_instance = LWE(n, q, m, D_e, D_s, is_ring = True)
    else:
        lwe_instance = LWE(n, q, m, D_e, D_s, is_ring = False)

    b, s, A, e_vec = (lwe_instance.b, lwe_instance.s, lwe_instance.A, lwe_instance.e_vec)

    # Custom Embedding
    b = matrix(b).apply_map(recenter)
    A = matrix(A).apply_map(recenter)
    v = np_randint(int(-q/_sage_const_2 ), int(q/_sage_const_2 ), n+m).tolist() # Converts to a numpy ndarray and then to a python list
    v = matrix(v) # Back to a matrix
    # v = matrix([randint(int(-q/2), int(q/2)) for i in range(n+m)])

    c = []
    #integrating hints
    print(s)
    for i in range(n):
        vi = concatenate([_sage_const_0 ]*i, q) #might need -q instead(?)
        vi = concatenate(vi, [_sage_const_0 ] * (n-i-_sage_const_1 ))
        vi = concatenate(vi, A[i])
        bi = b[_sage_const_0 ][i]
        ei = e_vec[_sage_const_0 ][i]

        # setting up ci
        ci1 = matrix(s[_sage_const_0 ]) * matrix(A[i]).T
        ci = -_sage_const_1 *(ci1[_sage_const_0 ,_sage_const_0 ] + ei-bi)/q
        c.append(ci)
        _ = our_ebdd.integrate_approx_hint(matrix(vi), int(bi), sigma**_sage_const_2 )

    #checking ellipsoid norm for all c||s
    u = concatenate(c, s)
    our_ebdd.u = u
    norm = our_ebdd.ellip_norm()/d
    #norm = scal((u - mu) * Sigma.inverse() * (u - mu).T)
    ebdd_norm = (norm)
    our_ebdd.estimate_attack()
    ebdd_predicted_beta_normal = (our_ebdd.beta)
    our_ebdd.estimate_attack(probabilistic = True)
    ebdd_predicted_beta_prob = (our_ebdd.beta)

    try:
        beta, delta = our_ebdd.attack(beta_max=_sage_const_80 )
    except ReductionError as e:
        beta = _sage_const_1 
        delta = _sage_const_1 
        print(f"Exception type: {type(e).__name__}")
    except Exception as err:
        beta = _sage_const_0 
        delta = _sage_const_0 
        print(f"Exception type: {type(err).__name__}")

    ebdd_calculated_beta = (beta)



    # Kannan's Embedding
    D_s = build_Gaussian_law(sigma, _sage_const_50 )
    D_e = D_s

    #embedding into EBDD
    ebdd_with_lwe = lwe_instance.embed_into_EBDD()

    #getting u, norm, and predicted betas
    u = concatenate(lwe_instance.s, lwe_instance.e_vec)
    norm = scal(matrix(u) * matrix(u.T))/((n+m)*sigma**_sage_const_2 ) 
    kannan_norm = (float(norm)) 
    ebdd_with_lwe.estimate_attack()
    kannan_predicted_beta_normal = (ebdd_with_lwe.beta)
    ebdd_with_lwe.estimate_attack(probabilistic = True)
    kannan_predicted_beta_prob = (ebdd_with_lwe.beta)

    # run even with error
    try:
        beta, delta = ebdd_with_lwe.attack(beta_max=_sage_const_80 ) 
    except ReductionError as e:
        beta = _sage_const_1 
        delta = _sage_const_1 
        print(f"Exception type: {type(e).__name__}")
    except Exception as err:
        beta = _sage_const_0 
        delta = _sage_const_0 
        print(f"Exception type: {type(err).__name__}")

    kannan_calculated_beta = (beta)

    end = time.time()
    length = (end-start)


    return (seed, ebdd_predicted_beta_normal, ebdd_predicted_beta_prob, ebdd_calculated_beta, ebdd_norm, kannan_predicted_beta_normal, kannan_predicted_beta_prob, kannan_calculated_beta, kannan_norm, length)




def run_experiment(num_experiments):

    ebdd_predicted_betas_normal = []
    ebdd_predicted_betas_prob = []
    ebdd_calculated_betas = []
    ebdd_norms = []
    kannan_predicted_betas_normal = []
    kannan_predicted_betas_prob = []
    kannan_calculated_betas  = []
    kannan_norms = []
    times = []
    seeds = []

    queue = []
    seedgen = _sage_const_34 
    with ProcessPoolExecutor(max_workers=cpu_count()) as pool:
        try: 
            for i in range(num_experiments):
                future = pool.submit(one_experiment, seed = seedgen + i)
                queue.append(future)
            for future in as_completed(queue):
                (seed, ebdd_predicted_beta_normal, ebdd_predicted_beta_prob, ebdd_calculated_beta, ebdd_norm, kannan_predicted_beta_normal, kannan_predicted_beta_prob, kannan_calculated_beta, kannan_norm, length) = future.result()
                seeds.append(seed)
                ebdd_predicted_betas_normal.append(ebdd_predicted_beta_normal)
                ebdd_predicted_betas_prob.append(ebdd_predicted_beta_prob)
                ebdd_calculated_betas.append(ebdd_calculated_beta)
                ebdd_norms.append(ebdd_norm)
                kannan_predicted_betas_normal.append(kannan_predicted_beta_normal)
                kannan_predicted_betas_prob.append(kannan_predicted_beta_prob)
                kannan_calculated_betas.append(kannan_calculated_beta)
                kannan_norms.append(kannan_norm)
                times.append(length)

        except Exception as e:
            from traceback import print_exc
            print("unknown exception in context execution")
            print_exc()
        finally:
            d = {"Seed": seeds, "EBDD Normal Predicted Beta": ebdd_predicted_betas_normal, "EBDD Probabilistic Predicted Beta": ebdd_predicted_betas_prob, "EBDD Calculated Beta": ebdd_calculated_betas, "EBDD Norms": ebdd_norms, "Kannan Normal Predicted Beta": kannan_predicted_betas_normal, "Kannan Prob Predicted Beta": kannan_predicted_betas_prob, "Kannan Calculated Beta": kannan_calculated_betas, "Kannan Norms": kannan_norms, "Times": times}
            df = pd.DataFrame(data=d)
            df.to_csv('ebdd_cluster.csv', index = True)
            sys.exit(_sage_const_0 )

if __name__ == "__main__":
    run_experiment(nb_tests)




